#!/usr/bin/env bash
# Batch-run ROSE, EffectErase, and ProPainter on ROSE-Benchmark layout:
#   Benchmark/<category>/{Unedited,Masked}/example-*.mp4
# Outputs:
#   Benchmark/<category>/predicted/rose/example-*.mp4   (basename = Unedited; ROSE one clip per process)
#   Benchmark/<category>/predicted/propainter/example-*.mp4
#   Benchmark/<category>/predicted/effecterase/example-*.mp4
#
# Requires: conda envs rose, effecterase, propainter; CUDA; weights as in EffectErase test_remove.sh.
# Usage (from anywhere):
#   bash /hpc2hdd/home/mli861/cv_project/inference_all.sh
# Optional: CUDA_VISIBLE_DEVICES=0 bash ...

set -euo pipefail

ROOT="/hpc2hdd/home/mli861/cv_project"
BENCH="${ROOT}/ROSE-Benchmark/Benchmark"
ROSE_DIR="${ROOT}/ROSE"
EE_DIR="${ROOT}/EffectErase"
PP_DIR="${ROOT}/ProPainter"

# DAVIS videos (generated by frames2video.py):
#   DAVIS/videos/images/*.mp4
#   DAVIS/videos/masks/*.mp4
# Outputs:
#   DAVIS/predicted/{rose,effecterase,propainter}/*.mp4
RUN_DAVIS="${RUN_DAVIS:-1}"
RUN_BENCH="${RUN_BENCH:-1}"
DAVIS_ROOT="${ROOT}/DAVIS"
DAVIS_IMG_VID_DIR="${DAVIS_ROOT}/videos/images"
DAVIS_MASK_VID_DIR="${DAVIS_ROOT}/videos/masks"
DAVIS_OUT_ROOT="${DAVIS_ROOT}/predicted"

# EffectErase checkpoints (same as EffectErase/script/test_remove.sh); override if needed:
export WAN_MODEL_ROOT="${WAN_MODEL_ROOT:-Wan-AI/Wan2.1-Fun-1.3B-InP}"
TEXT_ENC="${WAN_MODEL_ROOT}/models_t5_umt5-xxl-enc-bf16.pth"
VAE_P="${WAN_MODEL_ROOT}/Wan2.1_VAE.pth"
DIT_P="${WAN_MODEL_ROOT}/diffusion_pytorch_model.safetensors"
IMG_ENC="${WAN_MODEL_ROOT}/models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth"
LORA_P="${LORA_P:-${EE_DIR}/EffectErase.ckpt}"

if [[ "$RUN_BENCH" == "1" && ! -d "$BENCH" ]]; then
  echo "[ERROR] Benchmark root not found: $BENCH"
  exit 1
fi

# conda activate/deactivate scripts (e.g. gcc_linux-64) reference vars that may be unset;
# with `set -u` that becomes "unbound variable". Disable nounset around conda only.
# shellcheck disable=SC1091
set +u
eval "$(conda shell.bash hook)"
set -u

# --- per-method stats (videos = clips processed; sec = wall time for that method only) ---
declare -i ROSE_VIDEOS=0 ROSE_SEC=0
declare -i EE_VIDEOS=0 EE_SEC=0
declare -i PP_VIDEOS=0 PP_SEC=0

avg_sec() {
  local num=$1 den=$2
  [[ "$den" -gt 0 ]] || { echo "n/a"; return; }
  awk -v t="$num" -v c="$den" 'BEGIN { printf "%.2f", t / c }'
}

fmt_hms() {
  local s=$1
  [[ "$s" -ge 0 ]] || return
  printf '%dh%02dm%02ds' $((s / 3600)) $(((s % 3600) / 60)) $((s % 60))
}

# Bash glob order follows directory entry order (readdir), e.g. example-10 before example-1.
# Never iterate raw example-*.mp4 for anything that depends on numeric id order.
sorted_example_mp4s_in_dir() {
  local dir="$1"
  shopt -s nullglob
  local f b n
  for f in "$dir"/example-*.mp4; do
    b=$(basename "$f" .mp4)
    if [[ "$b" =~ ^example-[0-9]+$ ]]; then
      n=${b#example-}
      printf '%d\t%s\n' "$n" "$f"
    else
      echo "[WARN] skip (expected example-<digits>.mp4): $f" >&2
    fi
  done | sort -n | cut -f2-
  shopt -u nullglob
}

sorted_mp4s_in_dir() {
  local dir="$1"
  shopt -s nullglob
  local f
  for f in "$dir"/*.mp4; do
    [[ -f "$f" ]] || continue
    printf '%s\n' "$f"
  done | sort
  shopt -u nullglob
}

run_rose_category() {
  local cat="$1"
  local uned="$BENCH/$cat/Unedited"
  local mask="$BENCH/$cat/Masked"
  local out="$BENCH/$cat/predicted/rose"
  mkdir -p "$out"

  local mp4s=()
  mapfile -t mp4s < <(sorted_example_mp4s_in_dir "$uned")
  if [[ ${#mp4s[@]} -eq 0 ]]; then
    echo "[SKIP] $cat: no example-<digits>.mp4 under Unedited"
    return 0
  fi

  local f base _t0 _t1 _dt
  for f in "${mp4s[@]}"; do
    base=$(basename "$f")
    [[ -f "$mask/$base" ]] || { echo "[WARN] $cat: missing mask $mask/$base — skip"; continue; }

    echo "========== ROSE  [$cat]  $base =========="
    _t0=$(date +%s)
    (
      set +u
      cd "$ROSE_DIR"
      conda activate rose
      python inference.py \
        --validation_videos "$f" \
        --validation_masks "$mask/$base" \
        --validation_prompts "" \
        --output_dir "$out"
    )
    _t1=$(date +%s)
    _dt=$((_t1 - _t0))
    ROSE_SEC+=_dt
    ROSE_VIDEOS+=1
    echo "[TIME] ROSE [$cat] $base ${_dt}s"
  done
}

run_effecterase_category() {
  local cat="$1"
  local uned="$BENCH/$cat/Unedited"
  local mask="$BENCH/$cat/Masked"
  local out_dir="$BENCH/$cat/predicted/effecterase"
  mkdir -p "$out_dir"

  local mp4s=()
  mapfile -t mp4s < <(sorted_example_mp4s_in_dir "$uned")
  for f in "${mp4s[@]}"; do
    local base out_p
    base=$(basename "$f")
    [[ -f "$mask/$base" ]] || { echo "[WARN] $cat EE: missing mask for $base"; continue; }
    out_p="$out_dir/$base"
    echo "========== EffectErase  [$cat]  $base =========="
    local _t0 _t1 _dt
    _t0=$(date +%s)
    (
      set +u
      cd "$EE_DIR"
      conda activate effecterase
      CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}" python examples/remove_wan/infer_remove_wan.py \
        --fg_bg_path "$f" \
        --mask_path "$mask/$base" \
        --output_path "$out_p" \
        --text_encoder_path "$TEXT_ENC" \
        --vae_path "$VAE_P" \
        --dit_path "$DIT_P" \
        --image_encoder_path "$IMG_ENC" \
        --pretrained_lora_path "$LORA_P"
    )
    _t1=$(date +%s)
    _dt=$((_t1 - _t0))
    EE_SEC+=_dt
    EE_VIDEOS+=1
    echo "[TIME] EffectErase [$cat] $base ${_dt}s"
  done
}

run_propainter_category() {
  local cat="$1"
  local uned="$BENCH/$cat/Unedited"
  local mask="$BENCH/$cat/Masked"
  local out="$BENCH/$cat/predicted/propainter"
  mkdir -p "$out"

  local mp4s=()
  mapfile -t mp4s < <(sorted_example_mp4s_in_dir "$uned")
  for f in "${mp4s[@]}"; do
    local base
    base=$(basename "$f")
    [[ -f "$mask/$base" ]] || { echo "[WARN] $cat PP: missing mask for $base"; continue; }
    echo "========== ProPainter  [$cat]  $base =========="
    local _t0 _t1 _dt
    _t0=$(date +%s)
    (
      set +u
      cd "$PP_DIR"
      conda activate propainter
      CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}" python inference_propainter.py \
        --video "$f" \
        --mask "$mask/$base" \
        --output "$out"
    )
    _t1=$(date +%s)
    _dt=$((_t1 - _t0))
    PP_SEC+=_dt
    PP_VIDEOS+=1
    echo "[TIME] ProPainter [$cat] $base ${_dt}s"
  done
}

run_davis_all_methods() {
  local images_dir="$DAVIS_IMG_VID_DIR"
  local masks_dir="$DAVIS_MASK_VID_DIR"
  local rose_out="$DAVIS_OUT_ROOT/rose"
  local ee_out="$DAVIS_OUT_ROOT/effecterase"
  local pp_out="$DAVIS_OUT_ROOT/propainter"

  if [[ ! -d "$images_dir" || ! -d "$masks_dir" ]]; then
    echo "[SKIP] DAVIS videos not found: $images_dir and/or $masks_dir"
    echo "       Generate first, e.g.: python ${ROOT}/frames2video.py --root ${DAVIS_ROOT} --overwrite"
    return 0
  fi

  mkdir -p "$rose_out" "$ee_out" "$pp_out"

  local mp4s=()
  mapfile -t mp4s < <(sorted_mp4s_in_dir "$images_dir")
  if [[ ${#mp4s[@]} -eq 0 ]]; then
    echo "[SKIP] DAVIS: no .mp4 under $images_dir"
    return 0
  fi

  local f base _t0 _t1 _dt
  for f in "${mp4s[@]}"; do
    base=$(basename "$f")
    [[ -f "$masks_dir/$base" ]] || { echo "[WARN] DAVIS: missing mask video $masks_dir/$base — skip"; continue; }

    echo "#################### DAVIS: $base ####################"

    echo "========== ROSE  [DAVIS]  $base =========="
    _t0=$(date +%s)
    (
      set +u
      cd "$ROSE_DIR"
      conda activate rose
      python inference.py \
        --validation_videos "$f" \
        --validation_masks "$masks_dir/$base" \
        --validation_prompts "" \
        --output_dir "$rose_out"
    )
    _t1=$(date +%s)
    _dt=$((_t1 - _t0))
    ROSE_SEC+=_dt
    ROSE_VIDEOS+=1
    echo "[TIME] ROSE [DAVIS] $base ${_dt}s"

    echo "========== EffectErase  [DAVIS]  $base =========="
    _t0=$(date +%s)
    (
      set +u
      cd "$EE_DIR"
      conda activate effecterase
      CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}" python examples/remove_wan/infer_remove_wan.py \
        --fg_bg_path "$f" \
        --mask_path "$masks_dir/$base" \
        --output_path "$ee_out/$base" \
        --text_encoder_path "$TEXT_ENC" \
        --vae_path "$VAE_P" \
        --dit_path "$DIT_P" \
        --image_encoder_path "$IMG_ENC" \
        --pretrained_lora_path "$LORA_P"
    )
    _t1=$(date +%s)
    _dt=$((_t1 - _t0))
    EE_SEC+=_dt
    EE_VIDEOS+=1
    echo "[TIME] EffectErase [DAVIS] $base ${_dt}s"

    echo "========== ProPainter  [DAVIS]  $base =========="
    _t0=$(date +%s)
    (
      set +u
      cd "$PP_DIR"
      conda activate propainter
      CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}" python inference_propainter.py \
        --video "$f" \
        --mask "$masks_dir/$base" \
        --output "$pp_out"
    )
    _t1=$(date +%s)
    _dt=$((_t1 - _t0))
    PP_SEC+=_dt
    PP_VIDEOS+=1
    echo "[TIME] ProPainter [DAVIS] $base ${_dt}s"
  done
}

if [[ "$RUN_BENCH" == "1" ]]; then
  # Categories: direct children of Benchmark that have both Unedited/ and Masked/
  CATS=()
  for d in "$BENCH"/*/; do
    [[ -d "$d" ]] || continue
    c=$(basename "$d")
    [[ -d "$BENCH/$c/Unedited" && -d "$BENCH/$c/Masked" ]] || continue
    CATS+=("$c")
  done
  if [[ ${#CATS[@]} -eq 0 ]]; then
    echo "[ERROR] No category folders with Unedited+Masked under $BENCH"
    exit 1
  fi
fi

declare -i WALL_START WALL_END
WALL_START=$(date +%s)

if [[ "$RUN_BENCH" == "1" ]]; then
  for cat in "${CATS[@]}"; do
    [[ -d "$BENCH/$cat/Unedited" && -d "$BENCH/$cat/Masked" ]] || continue
    echo "#################### Category: $cat ####################"
    run_rose_category "$cat"
    run_effecterase_category "$cat"
    run_propainter_category "$cat"
  done
else
  echo "[SKIP] Benchmark disabled (RUN_BENCH=$RUN_BENCH)"
fi

if [[ "$RUN_DAVIS" == "1" ]]; then
  echo "#################### DAVIS ####################"
  run_davis_all_methods
else
  echo "[SKIP] DAVIS disabled (RUN_DAVIS=$RUN_DAVIS)"
fi

WALL_END=$(date +%s)
declare -i WALL_SEC=$((WALL_END - WALL_START))

echo ""
echo "================================================================================"
echo "  INFERENCE_ALL  SUMMARY"
echo "================================================================================"
echo "  ROSE          videos: ${ROSE_VIDEOS}   total: ${ROSE_SEC}s  ($(fmt_hms "${ROSE_SEC}"))   avg/video: $(avg_sec "${ROSE_SEC}" "${ROSE_VIDEOS}")s"
echo "  EffectErase   videos: ${EE_VIDEOS}    total: ${EE_SEC}s   ($(fmt_hms "${EE_SEC}"))   avg/video: $(avg_sec "${EE_SEC}" "${EE_VIDEOS}")s"
echo "  ProPainter    videos: ${PP_VIDEOS}   total: ${PP_SEC}s   ($(fmt_hms "${PP_SEC}"))   avg/video: $(avg_sec "${PP_SEC}" "${PP_VIDEOS}")s"
echo "  ---"
echo "  Wall-clock (entire script): ${WALL_SEC}s  ($(fmt_hms "${WALL_SEC}"))"
echo "================================================================================"
echo "[DONE] All categories processed under $BENCH"
